### ISSUE TITLE
notification via mail doesn't work

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-restic#3]
Looking at the script and the Dockerfile, you use s-nail instead of msmtp of the base image.
In my installation, the s-nail command doesn't exist / the notification fails.
So I'm looking at either using a custom notification script or would it be a possibility to use msmtp instead?

**Comment by tiredofit** [comment]
Copy and paste strikes again from my gcds repo. I've switched over to using msmtp now in `1.2.4`

**Comment by joergmschulz** [comment]
see #5
