### ISSUE TITLE
new repository needs to be created manually

### ISSUE THREAD

**Issue by joergmschulz** [tiredofit/docker-restic#4]
in order to create a new backup, I needed to create the new repository manually inside the container
(something like restic -r .... init).
Isn't this done automatically?

Furthermore the command to create a user is: 
`server-user create <username> <password>`
not: 
`server-user <username> <password>`
I'll push a new readme.md because the current one has formatting issues anyway. Will be done when it's ready.

**Comment by tiredofit** [comment]
Repositories _should_ be created automatically - This might have broken with the independent repositories, I'll have to do some tests. Originally (and still works) is `REPOSITORY_PATH` and `REPOSITORY_PASS` which acts as a default for all...

Thanks for fixup on README..

**Comment by joergmschulz** [comment]
Fatal: unable to open config file: <config/> does not exist
Is there a repository at the following location?
